export const ROUTE_LABELS: Record<string, string> = {
  "/": "Dispatch HQ",
  "/dispatch": "Dispatch HQ",
  "/intake": "Intake HQ",
  "/now": "Now HQ",
  "/workflows": "Workflow Maps",
  "/ivr-builder": "IVR Builder",
  "/phone": "Call history",
  "/sms": "SMS history",
  "/team": "Team HQ",
  "/inbox": "SMS",
  "/customers": "Customer HQ",
  "/parts": "Parts catalog",
  "/agreements": "Service agreements",
  "/payments": "Payments",
  "/settings": "Settings",
  "/brochure": "Brochure admin",
  "/agent-training": "JARVIS settings",
  "/admin": "Admin",
  "/locations": "Catalog & Pricebook",
  "/copilot": "JARVIS",
  "/quick-quote": "Quote HQ",
  "/quote-builder": "Quote Builder",
  "/catalog": "Catalog & Pricebook",
  "/shopping-cart": "Catalog & Pricebook",
};
